//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class diem
    {
        public int id { get; set; }
        public string masv { get; set; }
        public string tensv { get; set; }
        public string monhoc { get; set; }
        public string lop { get; set; }
        public Nullable<double> diem1 { get; set; }
        public Nullable<double> diem2 { get; set; }
        public Nullable<double> diem3 { get; set; }
        public Nullable<double> diemtb { get; set; }
        public string ketqua { get; set; }
    }
}
