//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class giangvien
    {
        public byte[] anh { get; set; }
        public string magv { get; set; }
        public string tengv { get; set; }
        public string sdt { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string tenkhoa { get; set; }
        public string monday { get; set; }
        public string diachi { get; set; }
        public string matkhau { get; set; }
    }
}
