//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoc_phan
    {
        public string mahp { get; set; }
        public string tenhp { get; set; }
        public string namhoc { get; set; }
        public Nullable<int> sotinchi { get; set; }
    }
}
