//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Du_AnEntities : DbContext
    {
        public Du_AnEntities()
            : base("name=Du_AnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<diem> diems { get; set; }
        public virtual DbSet<giangvien> giangviens { get; set; }
        public virtual DbSet<hoc_phan> hoc_phan { get; set; }
        public virtual DbSet<hocphi> hocphis { get; set; }
        public virtual DbSet<khoa> khoas { get; set; }
        public virtual DbSet<lop> lops { get; set; }
        public virtual DbSet<sinhvien> sinhviens { get; set; }
    }
}
